# Generated by Django 4.2.5 on 2023-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hireermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireermodel',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
