# Generated by Django 4.2.5 on 2023-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_catagory_list_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='skill',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='logo',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='mobile',
            field=models.BigIntegerField(default=''),
        ),
    ]
