# Generated by Django 4.2.5 on 2023-12-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_signupmodel_skill_alter_jobmodel_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='recuiredage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='recuiredskill',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='experince',
            field=models.TextField(default=''),
        ),
    ]
