# Generated by Django 4.2.5 on 2023-12-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobmodel_recuiredage_jobmodel_recuiredskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='zip',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
