# Generated by Django 4.2.5 on 2023-12-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_signupmodel_zip_alter_signupmodel_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='zip',
        ),
    ]
