# Generated by Django 4.2.5 on 2023-12-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_signupmodel_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='zip',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
