# Generated by Django 4.2.5 on 2023-12-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_signupmodel_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('zip', models.BigIntegerField()),
                ('skill', models.TextField()),
                ('experince', models.TextField()),
                ('age', models.TextField()),
                ('applyto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='zip',
            field=models.BigIntegerField(default=1),
        ),
    ]
