# Generated by Django 4.2.5 on 2023-12-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_applymodel_alter_signupmodel_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applymodel',
            name='cv',
        ),
    ]
