# Generated by Django 4.2.5 on 2023-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_applymodel_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymodel',
            name='experince',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='experince',
            field=models.BigIntegerField(default=''),
        ),
    ]
