# Generated by Django 4.2.5 on 2024-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_applymodel_experince_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
