# Generated by Django 4.2.5 on 2024-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_signupmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='cv',
            field=models.FileField(default='', upload_to='cv'),
        ),
    ]
