# Generated by Django 4.2.5 on 2024-01-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_business_name_hireermodel_hired_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireermodel',
            old_name='hired_by',
            new_name='business_name',
        ),
    ]
