# Generated by Django 4.2.5 on 2024-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_applymodel_created_hiredmodel_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applymodel',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='hiredmodel',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='applymodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hiredmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
