# Generated by Django 4.2.5 on 2024-01-10 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_created_applymodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='applied_for',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
