# Generated by Django 4.2.5 on 2024-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_applymodel_applied_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymodel',
            name='id_of_job',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
