# Generated by Django 4.2.5 on 2024-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_applymodel_id_of_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
