# Generated by Django 4.2.5 on 2024-02-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_signupmodel_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='VerificationToken',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
