# Generated by Django 4.2.5 on 2024-02-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_signupmodel_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
