# Generated by Django 4.2.5 on 2024-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_signupmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='PassresetToken',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
