# Generated by Django 4.2.5 on 2024-02-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_feedbackmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireermodel',
            name='passresetToken',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
